id: A402800D3
title: Toh_86-The_Question_of_Maitreya_on_the_Eight_Qualities-v1
type: translation
pechas:
- I14CE480E
- ID2C7C917
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: tei
  datatype: Text
  eft-text-id: UT22084-044-006
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_86-The_Question_of_Maitreya_on_the_Eight_Qualities-v1
alignment_to_base:
  I14CE480E/D80D: ACCA
  ID2C7C917/779F: ACCA
